{{- if .Values.admission.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-admission-init
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: admission-init
    {{- if .Values.global.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.global.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- include "volcano.admission.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "volcano.admission.serviceAccountName" . }}
      enableServiceLinks: {{ .Values.global.enableServiceLinks | default false }}
      {{- if .Values.admission.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.admission.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        {{- if .Values.admission.podAffinityPreset }}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.admission.podAffinityPreset "component" "admission-init" "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.admission.podAntiAffinityPreset }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.admission.podAntiAffinityPreset "component" "admission-init" "context" $) | nindent 10 }}
        {{- end }}
        {{- if and .Values.admission.nodeAffinityPreset .Values.admission.nodeAffinityPreset.key }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.admission.nodeAffinityPreset.type "key" .Values.admission.nodeAffinityPreset.key "values" .Values.admission.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.admission.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.admission.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.admission.priorityClassName }}
      priorityClassName: {{ .Values.admission.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.admission.schedulerName }}
      schedulerName: {{ .Values.admission.schedulerName }}
      {{- end }}
      {{- if .Values.admission.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.admission.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.admission.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.admission.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          image: "{{ .Values.admission.image.registry }}/{{ .Values.admission.image.repository }}:{{ .Values.admission.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - "./gen-admission-secret.sh"
            - "--service"
            - "{{ .Release.Name }}-admission"
            - "--namespace"
            - "{{ .Release.Namespace }}"
            - "--secret"
            - "{{ tpl .Values.admission.config.secretName . }}"
{{- end }}
