apiVersion: v2
description: A Helm chart for Volcano
name: volcano
version: 0.0.6
appVersion: v1.6.0
icon: https://raw.githubusercontent.com/volcano-sh/charts/master/docs/images/volcano-logo.png
home: https://volcano.sh
sources:
  - https://github.com/volcano-sh/volcano
  - https://github.com/DimkaGorhover/volcano-helm-chart
maintainers:
  - name: Dmytro Horkhover
    email: gd.mail.89@gmail.com
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
