apiVersion: v2
description: A Helm chart for Volcano
name: volcano
version: 0.0.5
appVersion: v1.6.0
icon: https://raw.githubusercontent.com/volcano-sh/charts/master/docs/images/volcano-logo.png
home: https://volcano.sh
sources:
  - https://github.com/volcano-sh/volcano
maintainers:
  - name: k82cn
    email: klaus1982.cn@gmail.com
  - name: kevin-wangzefeng
    email: kevinwzf0126@gmail.com
  - name: Dmytro Horkhover
    email: gd.mail.89@gmail.com
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
