{{- if and .Values.rbac (eq true .Values.rbac.create) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}-provisioner
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumeclaims
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
      - persistentvolumes
      - pods
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
{{- end }}
