apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  namespace: "{{ include "common.names.namespace" . }}"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}

data:
  config.json: |-
    {{- $nodePathMap := dict "nodePathMap" .Values.config.nodePathMap }}
    {{- $nodePathMap = (tpl (toYaml $nodePathMap) . | fromYaml) }}
    {{- if (eq true .Values.config.pretty) }}
    {{- $nodePathMap | toPrettyJson | nindent 4 }}
    {{- else }}
    {{ toJson $nodePathMap }}
    {{- end }}

  helperPod.yaml: |
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: {{ include "common.names.fullname" . }}-helper-pod
      namespace: "{{ include "common.names.namespace" . }}"
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: helper-pod
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      enableServiceLinks: false
      {{- if and .Values.rbac (eq true .Values.rbac.create) }}
      serviceAccountName: {{ include "common.names.fullname" . }}-provisioner
      {{- end }}
      containers:
        - name: helper-pod
          image: {{ include "local-path.helper.image" . }}
          imagePullPolicy: IfNotPresent
          {{- if and .Values.helper .Values.helper.containerSecurityContext .Values.helper.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.helper.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.helper.resources }}
          resources:
            {{- toYaml .Values.helper.resources | nindent 12 }}
          {{- end }}

  setup: |-
    {{- .Values.config.setupScript | nindent 4 }}

  teardown: |-
    {{- .Values.config.teardownScript | nindent 4 -}}
